package com.optimization.objects.blockchain.model;

public enum EventType {
	REGISTRATION_ADDED,
	REGISTRATION_REMOVED,
	NMF_CONNECTION_ESTABLISHED,
	REGULATION_ADDED,
	OPTIMIZATION_INITIALISED,
	OPTIMIZATION_STARTED,
	OPTIMIZATION_RESULTS_RECEIVED,
	VETO_RECEIVED,
	SOLUTIONS_SUBMITTED,
	SOLUTION_ACCEPTED
}
